### ISSUE TITLE
Depenencies

### ISSUE THREAD

**Issue by Delaroyas** [Delaroyas/simplyslopes#3]
Must included soft dependencies in the depends.txt. Check if "default" is really a dependency.

**Comment by Delaroyas** [comment]
Checked optionnal mods, "mobs" and "lapis" "moreblocks","bakedclay", "castle", "homedecor"and "wool" they are ok.

**Comment by Delaroyas** [comment]
Failed to run homedecor (the mod itself)
Fixed.

**Comment by Delaroyas** [comment]
Etheral seams to have no effect

**Comment by Delaroyas** [comment]
Could not find a "xanadu" mod...

**Comment by Delaroyas** [comment]
default:pinewood and default:obsidianbrick nodes don't exist

**Comment by 0-afflatus** [comment]
There is no xanadu mod AFAIK
Sounds like you need to update to the dev version of minetest_game

**Comment by Delaroyas** [comment]
The reference to the "xanadu" mod comes from the stairs mod I used as a template for my mod. (From tenplus1). There are a few blocs identified as xandadu:blablablah and other from baked clay only if xanadu mod is present...

I updated the "default" mod , fixed default:pinewood  but default:obsidianbrick  still is non-existant.

**Comment by 0-afflatus** [comment]
default:obsidianbrick exists in default. It has been there for at least 6 months.

**Comment by Delaroyas** [comment]
Anyway the code for default:obsidianbrick is already there, I even added something so the slope nodes are created only if parent node exists.

**Comment by Delaroyas** [comment]
Fixed "castle", updated minetest, solved default:obsidianbrick and HomeDecor. Thanks for the tip. 0-afflatus

**Comment by Delaroyas** [comment]
"xanadu" mod was converted using the new functions but never tested.
