### ISSUE TITLE
Simplify nodenames

### ISSUE THREAD

**Issue by 0-afflatus** [Delaroyas/simplyslopes#8]
The naming pattern "simplyslopes:slope_<subname>" creates very long nodenames and prepending slope_ doesn't add any useful information (plus you haven't consistently used the underscore).

May I suggest just "simplyslopes:<subname>" would be sufficient?

**Comment by Delaroyas** [comment]
Tanks I agree the names are long.
I do think I will redo the naming convention.
Also thought Id drop any "block" in the description and subname
Note that I rewrote the functions so I copy the parent node properties now, so I will be use the mods 
_ usage.

I do need to differentiate regular slopes from the 4 different types of corners. So maybe:
simplyslopes:<subname>
simplyslopes:corner_<subname>
simplyslopes:corner2_<subname>
simplyslopes:innercorner_<subname>
simplyslopes:innercorner2_<subname> ?

Or assuming if it's not a regular slope, it's surely a corner:
simplyslopes:<subname>
simplyslopes:outer_<subname>
simplyslopes:outer2_<subname>
simplyslopes:inner_<subname>
simplyslopes:inner2_<subname> ?

**Comment by 0-afflatus** [comment]
Yep. I like the second version, simply because it means less typing if using /give.
Either way is better.

I've been using the latest version with simplyslopes.register_all2(). 
It's very neat - I can't quite figure how you did that but nvm.

**Comment by Delaroyas** [comment]
The key is using:
local thisnode=minetest.registered_nodes[recipeitem]

Which gets all the properties of the parent. So I can use:
thisnode.groups, thisnode.tiles, thisnode.description, thisnode.sounds to create the new nodes.

**Comment by Delaroyas** [comment]
Used this as a naming convention:
simplyslopes:outer_
simplyslopes:outer2_
simplyslopes:inner_
simplyslopes:inner2_

Should I remove the _ from the original  subname?
Should I remove the word "block" from original subname?
Should I remove the word "plank" from original subname?

**Comment by 0-afflatus** [comment]
I think leave the original subnames as is.
Having a logical scheme that relates to the original block names is much easier to remember.

**Comment by Delaroyas** [comment]
Ok then issue closed.
