### ISSUE TITLE
Simplify selection box

### ISSUE THREAD

**Issue by 0-afflatus** [Delaroyas/simplyslopes#9]
Having the selection box matching the collision box is unnecessary.
It makes it difficult to see what you're doing.
A simple cube would be much better IMO.

**Comment by Delaroyas** [comment]
I tough so to at first, I tried it, but it makes it impossible to place blocks "behind" slopes, if the hitbox "hides" the block.  Even with these small stairs it's not always easy while building. But using lots of small steps  looks horrible. So this is the compromise I came up with.

**Comment by 0-afflatus** [comment]
OK, closing then.
